---
output:: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## `tvthemes` : Themes and Color Palettes based on American TV Shows for `ggplot2` visualizations

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(tvthemes)
library(extrafont)
# import_univers()
# import_univers_extrablack()
# import_champion_htf_heavyweight()
# import_simpsons()
loadfonts()
```

# b99

```{r}
mtcars %>% 
  mutate(cyl = as_factor(cyl),
         carb = as_factor(carb)) %>% 
  ggplot(aes(mpg, hp, fill = cyl)) +
  #geom_point(aes(color = carb), size = 2) +
  geom_point(size = 2, color = "#41b6c4") +
  geom_rect(aes(xmin = 100, xmax = 300, ymin = 200, ymax = 300)) +
  scale_color_brooklyn99() +
  scale_fill_brooklyn99() +
  labs(x = "horsepowerinho", y = "mile per gallones",
       title = "Well this package thing isn't going all dandy and sunshines") +
  theme_brooklyn99(font.text = "Roboto Condensed",
                   font.title = "Champion HTF-Heavyweight",
                   font.legend = "Helvetica")
```

# b99 dark

```{r}
mpg %>% 
  ggplot(aes(displ)) +
  geom_histogram(aes(fill = class), 
                 col = "black", size = 0.1,
                 binwidth = 0.1) +
  scale_fill_brooklyn99_dark() +
  theme_brooklyn99()
```


# ?


```{r}
mtcars %>% 
  mutate(cyl = as_factor(cyl),
         carb = as_factor(carb)) %>% 
  ggplot(aes(mpg, hp, fill = cyl)) +
  #geom_point(aes(color = carb), size = 2) +
  geom_col(fill = "#549E39") +
  geom_point(size = 2, color = "#41b6c4") +
  geom_rect(aes(xmin = 100, xmax = 300, ymin = 200, ymax = 300)) +
  theme(text = element_text(family = "Champion HTF-Heavyweight"),
        axis.text = element_text(size = 8),
        axis.title.y = element_text(angle = 0, vjust= 0.5),
        plot.background = element_rect(color = NA, fill = "#fcf7e8"),
        panel.background = element_rect(color = NA, fill = "#fcf7e8"),
        panel.grid.major.x = element_blank())
```

# p&r normal

```{r}
# mtcars %>% 
#   mutate(cyl = as_factor(cyl),
#          carb = as_factor(carb)) %>% 
  # ggplot(aes(mpg, hp)) +
  # #geom_point(aes(color = carb), size = 2) +
  # geom_col(fill = "#4C3114") + # "#549E39" lightgreen
  # geom_point(size = 2, color = "#7A491E") +   #  #4C3114 darker brown
  # geom_point(color = "yellow") +
  # geom_point(color = "#fee0d2") +
mpg %>% 
  ggplot(aes(displ)) +
  geom_histogram(aes(fill = class), col = "black", size = 0.1) +
  labs(title = "Parks and Recreation",
       subtitle = "blahblah Leslie Knope") +
  theme(text = element_text(family = "Akbar"),
        plot.subtitle = element_text(color = "grey20"),
        axis.text = element_text(size = 8, color = "grey20"),
        axis.title = element_text(color = "grey20"),
        plot.background = element_rect(color = NA, fill = "#CCFFBB"),#238443   #CCFFBB
        panel.background = element_rect(color = NA, fill = "#238443"), # #1A5E1FFF darkgreen  #238443
        panel.grid.major = element_line(color = "#fee0d2"),
        panel.grid.minor = element_line(color = "#fee0d2")) +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_continuous(expand = c(0,0)) +
  scale_fill_parksAndRec()
```

# p&r light

```{r}
mpg %>% 
  ggplot(aes(displ)) +
  geom_histogram(aes(fill = class), col = "black", size = 0.1) +
  labs(title = "Parks and Recreation",
       subtitle = "blahblah Leslie Knope") +
  theme(text = element_text(family = "Champion HTF-Heavyweight", color = "#fee8c8"),
        axis.text = element_text(size = 8, color = "#fee8c8"),
        axis.title = element_text(color = "#fee8c8"),
        plot.background = element_rect(color = NA, fill = "#41ab5d"),#238443   #CCFFBB
        panel.background = element_rect(color = NA, fill = "#CCFFBB"), # #1A5E1FFF darkgreen  #238443
        panel.grid.major = element_line(color = "grey20"),
        panel.grid.minor = element_line(color = "grey20"),
        legend.title = element_text(color = "grey20"),
        legend.text = element_text(color = "grey20", size = 9)) +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_continuous(expand = c(0,0)) +
  scale_fill_parksAndRec()
```


# P&R logo

```{r}
library(shadowtext)
library(glue)

header <- ggplot() +
  geom_shadowtext(aes(y = 3.15, x = 2,
           family = "Champion HTF-Heavyweight"), 
           color = "#fcf7e8", size = 50,
           label = glue("Parks & Recreation")) +
  # annotate(geom = "text", y = 3.15, x = 2, size = 50, 
  #          family = "Champion HTF-Heavyweight", color = "#fcf7e8",
  #          label = glue("Parks & Recreation")) +
  geom_shadowtext(aes(y = 3.15, x = 2,
           family = "Champion HTF-Heavyweight"), 
           color = "#fcf7e8", size = 25,
           label = glue("Parks & Recreation")) +
  # annotate(geom = "text", y = 2.5, x= 2, size = 25, 
  #          family = "Champion HTF-Heavyweight", color = "white",
  #          label= "Parks & Recreation") +
  ylim(0, 4) +
  theme_void() +
  theme(plot.background = element_rect(color = "#fcf7e8", 
                                       fill = "#005502", # "#1A5E1FFF" "#CCFFBB"
                                       size = 5))
header
```



# The Simpsons

```{r}
mpg %>% 
  ggplot(aes(displ)) +
  geom_histogram(aes(fill = class), col = "black", size = 0.1) +
  #geom_bar(fill = "#FFD235") +
  labs(title = "Los Simpsons",
       subtitle = "blahblah Homer Simpson Sector 7G skateboard") +
  theme(text = element_text(family = "Akbar", color = "#fee8c8"),
        axis.text = element_text(size = 8, color = "#fee8c8"),
        axis.title = element_text(color = "#fee8c8"),
        plot.title = element_text(color = "#FFD235"),
        plot.background = element_rect(color = NA, fill = "#7199E1"),#238443   #CCFFBB
        panel.background = element_rect(color = NA, fill = "#7199E1"), 
        panel.grid.major = element_line(color = "#fee8c8"),
        panel.grid.minor = element_line(color = "#fee8c8"),
        legend.title = element_text(color = "grey20"),
        legend.text = element_text(color = "grey20", size = 9),
        legend.key = element_rect(colour = "black", linetype = "solid", size = 1.5),
        legend.background = element_rect(color = "black", fill = "#7199E1",
                                         linetype = "solid")) +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_continuous(expand = c(0,0)) +
  scale_fill_simpsons() +
  scale_fill_parksAndRec()
```




# The Good Place

- Pobody's Nerfect t-shirt color scheme (yellow/purple/brown/darknavy)


```{r}
mpg %>% 
  ggplot(aes(displ)) +
  geom_histogram(aes(fill = class), col = "black", size = 0.1) +
  #geom_bar(fill = "#FFD235") +
  labs(title = "Rick and Morty",
       subtitle = "blahblah Gazorpazorp Summer goddamit") +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_continuous(expand = c(0,0)) +
  scale_fill_rickAndMorty() + theme_minimal()
  scale_fill_simpsons() +
  theme(text = element_text(family = "Some Time Later"))
```

